version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: shoes/catalog
    build:
      context: .\src\Services\ProductCatalogApi
      dockerfile: Dockerfile
    environment:
      - ConnectionString=server=mssqlserver;Database=CatalogDb;User Id=sa;Password=MyProduct123!;MultipleActiveResultSets=true
    ports: 
      - "8080:80"
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build: 
      context: .\src\Web\WebMvc
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
      - CatalogUrl=http://catalog
    container_name: webshop
    ports:
      - "5500:80"
    networks:
      - frontend 
    depends_on:
      - catalog 

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
   
    environment:
      - SA_PASSWORD=MyProduct123!
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"

    networks:
      - backend
